######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 11 12:54:14 2014
######################################################################

TEMPLATE = app

TARGET = ./datagen.e

LIBS += ../../../lib/tinyxml.so


DEPENDPATH += .

INCLUDEPATH += .

# Input
SOURCES += datagen.cpp
